# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test IP Pool
#
- hosts: localhost
  become: yes
  collections:
    - vmware.ansible_for_policy_nsxt
  tasks:
    - name: create IP Pool
      nsxt_ip_pool:
        hostname: "default"
        username: "default"
        password: "default"
        validate_certs: False
        display_name: test-ip-pool-1
        state: "present"
        tags:
        - tag: "a"
          scope: "b"
        pool_block_subnets:
          - id: test-ip-subnet-1
            state: present
            ip_block_id: "test-ip-blk-1"
            size: 16
          - display_name: test-ip-subnet-2
            state: present
            ip_block_id: "test-ip-blk-1"
            size: 16
          - display_name: test-ip-subnet-3
            state: present
            ip_block_id: "test-ip-blk-1"
            size: 8