---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile-upgrade.yml
  tasks:

#  #############  Upgrade Host Unite Group 2 #############

    - name: Start Upgrade
      upgrade_start_upgrade:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"

    - name: Upgrade Status
      upgrade_status:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"
          component_type: "HOST"


#  #############  Upgrade Edge Phase #############

    - name: Start Upgrade
      upgrade_start_upgrade:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"

    - name: Upgrade Status
      upgrade_status:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"
          component_type: "EDGE"


#  #############  Upgrade MP Phase #############

    - name: Start Upgrade
      upgrade_start_upgrade:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"

    - name: Upgrade Status
      upgrade_status:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"
          component_type: "MP"


#  ###########  Upgrade Finalization Phase ############

    - name: Start Upgrade
      upgrade_start_upgrade:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"

    - name: Upgrade Status
      upgrade_status:
          hostname: "{{upgrade_ip_address}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: "{{validate_certs}}"
          component_type: "MP"


#  #############  Run Post-check #############

    - name: Run Post-check
      upgrade_run_post_check:
            hostname: "{{upgrade_ip_address}}"
            username: "{{username}}"
            password: "{{password}}"
            validate_certs: "{{validate_certs}}"
            component_type: "MP"
